# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onUtuNMiTVB6s70fqsYM-gUUXAoTvPl-
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset - Example with a hypothetical path, replace with your actual path
df = pd.read_csv('/content/test.csv')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# Load dataset - Example with a hypothetical path, replace with your actual path
df = pd.read_csv('/content/gender_submission.csv')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset - Example with a hypothetical path, replace with your actual path
df = pd.read_csv('/content/train.csv')

# View first few records
df.head()

# General info
df.info()

# Statistical summary
df.describe()

# Missing values
df.isnull().sum()

# Count of unique values per column
df.nunique()

# Categorical counts
df['Sex'].value_counts()
df['Embarked'].value_counts()

sns.countplot(x='Sex', data=df)
plt.title('Gender Distribution')
plt.show()

sns.countplot(x='Pclass', data=df)
plt.title('Passenger Class Distribution')
plt.show()

sns.countplot(x='Survived', data=df)
plt.title('Survival Count')
plt.show()

df['Age'].hist(bins=30)
plt.title('Age Distribution')
plt.xlabel('Age')
plt.show()

sns.boxplot(y='Fare', data=df)
plt.title('Fare Boxplot')
plt.show()

# Age vs Survived
sns.boxplot(x='Survived', y='Age', data=df)
plt.title('Survival by Age')
plt.show()

# Pclass vs Survived
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title('Survival by Passenger Class')
plt.show()

# Sex vs Survived
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title('Survival by Gender')
plt.show()

# Pairplot
sns.pairplot(df[['Survived', 'Pclass', 'Age', 'Fare']], hue='Survived')
plt.show()

# Correlation heatmap
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

